# Базовые настройки
version: 0.0.20
title: Портфолио Sergio Eliofery
description: Портфолио и блог web разработчика Sergio Eliofery.
lang: ru
url: 'https://eliofery.github.io'
baseurl: '/jekyll-portfolio'
themecolor: '#ee1b24'
permalink: /blog/:name-:categories.html # https://jekyllrb.com/docs/permalinks/#built-in-formats

# export JEKYLL_ENV=production|development
google_analytics: UA-XXXXXXXXX-X
yandex_metrika: XXXXXX

# Коллекции
# См. параметр jekyll_compose ниже
collections:
  portfolio:
    output: true
    permalink: /:collection/:name-:i_day:i_month:short_year

# Режим разработки
liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

# Настройки плагинов
plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-inline-svg
  - jekyll-webp
  - jekyll-image-size

# Подсветка синтаксиса
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Набор правил по умолчанию для создаваемых страниц через терминал
jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      description:
      image: cover.jpg
      alt: Основное изображение
      category:
      tags: []
      published: false
      sitemap: false
      excerpt_separator: <!--more-->
    posts:
      description:
      image: cover.jpg
      alt: Основное изображение
      category:
      tags: []
      published: true
      sitemap: true
      excerpt_separator: <!--more-->
    portfolio:
      layout: portfolio
      description:
      image: cover.jpg
      alt: Основное изображение
      work-year: 2023
      roles: []
      tags: []
      excerpt_separator: <!--more-->

# Пагинация
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Архивные страницы по годам и т.д.
jekyll-archives:
  enabled: [year]
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Оптимизация изображений
svg:
  optimize: true
webp:
  enabled: true
  quality: 75
  img_dir: ['/assets/img/', '/images/']
  nested: true
  formats: ['.jpeg', '.jpg', '.png']
  regenerate: false
  exclude: ['icons']
  append_ext: true

# Обрезка и изменение размера изображений
mini_magick:
  thumbnail:
    source: images/original
    destination: images/thumbnail
    resize: "530x390^"
    gravity: "center" # NorthWest, North, NorthEast, West, Center, East, SouthWest, South, SouthEast
    extent: "530x390"
  portfolio:
    source: images/original
    destination: images/portfolio
    resize: "550x450^"
    gravity: "center"
    extent: "550x450"
  full:
    source: images/original
    destination: images/full
    resize: "1920x500^"
    gravity: "center"
    extent: "1920x500"

# Включение файлов и каталогов в сборку _site
include:
  - _pages
  - .htaccess

# Исключение файлов и каталогов из сборки _site
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
